import { Component, ElementRef, ViewChild, OnDestroy } from '@angular/core';

@Component({
  selector: 'button-connect',
  imports: [],
  templateUrl: './button-connect.html',
  styleUrl: './button-connect.scss',
})
export class ButtonConnect implements OnDestroy {

  @ViewChild('videoElement') videoElement!: ElementRef<HTMLImageElement>;

  // A RTCPeerConnection uses a process called ICE (Interactive Connectivity Establishment)
  // to find the best possible path for two peers to connect, even if they are behind NATs (Network Address Translators) or firewalls.
  private iceConfig = {
    'iceServers': [
      { 'urls': 'stun:stun.l.google.com:19302' },
      { 'urls': 'stun:stun1.l.google.com:19302' }
    ]
  };

  private peerConnection!: RTCPeerConnection;
  private signalingSocket!: WebSocket;
  private dataChannel!: RTCDataChannel;
  
  // NOTE: Browsers block 'ws://' if the page is loaded via 'https://' (Mixed Content).
  // Since the ESP32 is using 'ws://', ensure this app is served via 'http://'.
  private signalServerUrl = 'ws://91.5.180.129:3000'; 
  
  private lastObjectUrl: string | null = null;

  ngOnDestroy(): void {
    this.closeConnection();
  }

  public onClick() {
    console.log('Starting connection process...');
    this.connectSignaling();
  }

  private connectSignaling() {
    this.signalingSocket = new WebSocket(this.signalServerUrl);

    this.signalingSocket.onopen = () => {
      console.log('Signaling WebSocket Connected');
      this.setupPeerConnection();
    };

    this.signalingSocket.onmessage = async (event) => {
      try {
        const message = JSON.parse(event.data);
        await this.handleSignalingMessage(message);
      } catch (err) {
        console.error('Failed to parse signaling message', err);
      }
    };

    this.signalingSocket.onerror = (err) => {
      console.error('Signaling WebSocket Error:', err);
    };
  }

  private async setupPeerConnection() {
    this.peerConnection = new RTCPeerConnection(this.iceConfig);

    // 1. Handle ICE Candidates generated by the browser
    this.peerConnection.onicecandidate = (event) => {
      if (event.candidate) {
        const payload = {
          candidate: event.candidate.candidate,
          sdpMid: event.candidate.sdpMid,
          sdpMLineIndex: event.candidate.sdpMLineIndex
        };
        this.sendSignalingMessage('candidate', payload);
      }
    };

    this.peerConnection.onconnectionstatechange = () => {
      console.log('Peer Connection State:', this.peerConnection.connectionState);
    };

    // 2. Create Data Channel (We are the Offerer)
    // The ESP32 is configured with manual_ch_create = false, so it waits for us.
    this.dataChannel = this.peerConnection.createDataChannel('video');
    this.setupDataChannelEvents();

    // 3. Create Offer
    const offer = await this.peerConnection.createOffer();
    await this.peerConnection.setLocalDescription(offer);

    // 4. Send Offer to ESP32 via Signaling Server
    // Note: offer.sdp is a string
    this.sendSignalingMessage('offer', offer.sdp);
  }

  private setupDataChannelEvents() {
    this.dataChannel.onopen = () => {
      console.log('Data Channel Open!');
    };

    this.dataChannel.onmessage = (event) => {
      // The ESP32 sends the JPEG binary directly
      this.renderImage(event.data);
    };
  }

  private renderImage(data: ArrayBuffer) {
    const blob = new Blob([data], { type: 'image/jpeg' });
    const url = URL.createObjectURL(blob);

    // Revoke the previous URL to avoid memory leaks
    if (this.lastObjectUrl) {
      URL.revokeObjectURL(this.lastObjectUrl);
    }
    this.lastObjectUrl = url;

    if (this.videoElement && this.videoElement.nativeElement) {
      this.videoElement.nativeElement.src = url;
    }
  }

  private async handleSignalingMessage(message: any) {
    const { type, payload } = message;

    if (type === 'answer') {
      console.log('Received Answer');
      await this.peerConnection.setRemoteDescription({ type: 'answer', sdp: payload });
    } else if (type === 'candidate') {
      console.log('Received ICE Candidate');
      await this.peerConnection.addIceCandidate(payload);
    }
  }

  private sendSignalingMessage(type: string, payload: any) {
    if (this.signalingSocket.readyState === WebSocket.OPEN) {
      const message = { type, payload };
      this.signalingSocket.send(JSON.stringify(message));
    }
  }

  private closeConnection() {
    if (this.dataChannel) this.dataChannel.close();
    if (this.peerConnection) this.peerConnection.close();
    if (this.signalingSocket) this.signalingSocket.close();
    
    if (this.lastObjectUrl) {
      URL.revokeObjectURL(this.lastObjectUrl);
      this.lastObjectUrl = null;
    }
  }
}
